import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CleverTapProvider from "./components/CleverTapProvider"; // Import the provider
import ServiceWorkerRegister from "./components/ServiceWorkerRegister";
import CleverTapIntegration from "./components/CleverTapIntegration";
import CsvUploader from "./components/CsvUploader";
import CleverTapObjectIdExtractor from "./components/objectid_extracter"
import CleverTapDemerge from "./components/demerge";
import SignedCall from "./components/SignedCall";
import CsvToApiUploader from "./components/CsvToApiUploader";
import NativeDisplayPage from "./components/NativeDisplayPage";
// import SignedCall from "./components/SignedCall";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <CleverTapProvider /> 
        <ServiceWorkerRegister />
        <NativeDisplayPage/>
        {/* <CleverTapProvider /> 
        <ServiceWorkerRegister />
        <SignedCall />
        <CleverTapIntegration/> */}
        {/* <CsvUploader/>
        <CleverTapObjectIdExtractor/>
        <CleverTapDemerge/>
        <CsvToApiUploader/> */}
        {children}
      </body>
    </html>
  );
}
